// Generated by CoffeeScript 1.3.1
(function() {

  describe('Hasty.Github', function() {
    beforeEach(function() {
      return this.github = new Hasty.Github('user', 'repo');
    });
    return describe('paths', function() {
      describe('API', function() {
        it('#repoAPIURL', function() {
          return expect(this.github.repoAPIURL()).toEqual('https://api.github.com/repos/user/repo');
        });
        it('#commitAPIURL', function() {
          return expect(this.github.commitAPIURL('123')).toEqual('https://api.github.com/repos/user/repo/123');
        });
        return it('#commitCommentsAPIURL', function() {
          return expect(this.github.commitCommentsAPIURL('123')).toEqual('https://api.github.com/repos/user/repo/123/comments');
        });
      });
      return describe('Web', function() {
        it('#repoWebURL', function() {
          return expect(this.github.repoWebURL()).toEqual('https://github.com/user/repo');
        });
        it('#commitCommentsWebURL', function() {
          return expect(this.github.commitCommentsWebURL('123')).toEqual('https://github.com/user/repo/commit/123#comments');
        });
        return it('#commitCommentWebURL', function() {
          return expect(this.github.commitCommentWebURL('123', '456')).toEqual('https://github.com/user/repo/commit/123#commitcomment-456');
        });
      });
    });
  });

}).call(this);
