// Generated by CoffeeScript 1.3.1
(function() {
  var Github;

  Github = (function() {

    Github.name = 'Github';

    function Github(user, repo) {
      var _ref;
      _ref = [user, repo], this.user = _ref[0], this.repo = _ref[1];
    }

    Github.prototype.repoAPIURL = function() {
      return "https://api.github.com/repos/" + this.user + "/" + this.repo;
    };

    Github.prototype.commitAPIURL = function(commitID) {
      return "" + (this.repoAPIURL()) + "/" + commitID;
    };

    Github.prototype.commitCommentsAPIURL = function(commitID) {
      return "" + (this.commitAPIURL(commitID)) + "/comments";
    };

    Github.prototype.repoWebURL = function() {
      return "https://github.com/" + this.user + "/" + this.repo;
    };

    Github.prototype.commitCommentsWebURL = function(commitID) {
      return "" + (this.repoWebURL()) + "/commit/" + commitID + "#comments";
    };

    Github.prototype.commitCommentWebURL = function(commitID, commentID) {
      return "" + (this.repoWebURL()) + "/commit/" + commitID + "#commitcomment-" + commentID;
    };

    return Github;

  })();

  window['Hasty'] || (window['Hasty'] = {});

  window['Hasty']['Github'] = Github;

}).call(this);
