// Generated by CoffeeScript 1.3.1
(function() {

  describe('hastie', function() {
    var $comments, COMMENTS_URL;
    $comments = null;
    COMMENTS_URL = 'https://api.github.com/repos/polarblau/hastie-test-blog/commits/71a795094eb8a04d7d41208aa5930ec257c73979/comments';
    describe('basic jQuery plugin functionality', function() {
      beforeEach(function() {
        setFixtures("<div id='comments' data-comments-url='" + COMMENTS_URL + "'></div>");
        return $comments = $('#comments').hastie();
      });
      return it('should be chainable', function() {
        $comments.addClass('foo');
        return expect($comments).toHaveClass('foo');
      });
    });
    return describe('API requests', function() {
      beforeEach(function() {
        return setFixtures("<div id='comments' data-comments-url='" + COMMENTS_URL + "'></div>");
      });
      return it('should make an AJAX request to COMMENTS_URL', function() {
        spyOn($, 'ajax');
        $comments = $('#comments').hastie();
        return expect($.ajax).toHaveBeenCalled();
      });
    });
  });

}).call(this);
