// Generated by CoffeeScript 1.3.1
(function() {

  describe('hastie', function() {
    return it('should be truthy', function() {
      return expect(true).toBeTruthy();
    });
  });

}).call(this);
