// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $.fn.hastie = function(options) {
    var settings;
    settings = $.extend({
      commentsTemplate: 'foo',
      commentTemplate: 'bar'
    });
    return this.each(function() {
      var $this, url;
      $this = $(this);
      url = $this.data('comments-url');
      return $.ajax({
        url: url,
        success: function(data) {
          return console.log(data);
        },
        dataType: 'jsonp'
      });
    });
  };

}).call(this);
