// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $.fn.hastie = function(options) {
    var defaultTemplate, render, settings;
    settings = $.extend({
      commentsTemplate: 'foo',
      commentTemplate: 'bar'
    });
    defaultTemplate = "{{#comments}}\n  * {{body}}\n{{/comments}}";
    render = function(comments, $container) {
      var output;
      output = Mustache.render(defaultTemplate, comments);
      console.log(comments, output);
      return $container.html(comments);
    };
    return this.each(function() {
      var $this, url;
      $this = $(this);
      url = $this.data('comments-url');
      return $.ajax({
        url: url,
        success: function(comments) {
          return render(comments.data, $this);
        },
        dataType: 'jsonp'
      });
    });
  };

}).call(this);
