// Generated by CoffeeScript 1.3.1
(function() {
  var $;

  $ = jQuery;

  $.fn.hasty = function(options) {
    var defaultTemplate, render, settings;
    settings = $.extend({
      perPage: 10
    });
    defaultTemplate = "<ul>\n  {{#comments}}\n    <li>{{body}}</li>\n  {{/comments}}\n</ul>";
    render = function(comments, $container) {
      var output;
      output = Mustache.render(defaultTemplate, {
        comments: comments
      });
      return $container.html(output);
    };
    return this.each(function() {
      var $this, comments, commitCommentsURL, commitIDs, commitsURL, loadAndRender;
      $this = $(this);
      commitsURL = $this.data('commits-url');
      commitIDs = $this.data('commit-ids');
      comments = [];
      commitCommentsURL = function(commitID) {
        return "" + commitsURL + "/" + commitID + "/comments";
      };
      loadAndRender = function() {
        var commitID;
        commitID = commitIDs.shift();
        console.log(commitCommentsURL(commitID));
        return $.ajax({
          url: commitCommentsURL(commitID),
          success: function(comments) {
            comments.push(comments.data);
            if (comments.length < settings.perPage) {
              return loadAndRender();
            } else {
              return render(comments, $this);
            }
          },
          dataType: 'jsonp'
        });
      };
      return loadAndRender();
    });
  };

}).call(this);
